service: sls-aws-lambda
provider:
  name: aws
  runtime: java8
  timeout: 10
package:
  artifact: target/aws-lambda-0.0.1-SNAPSHOT-aws.jar
functions:
  findOrderByName:
    handler: com.accenture.aws.lambda.OrderHandler
    environment:
      FUNCTION_NAME: findOrderByName

  orders:
    handler: com.accenture.aws.lambda.OrderHandler
    environment:
      FUNCTION_NAME: orders

  getApiResponse:
    handler: com.accenture.aws.lambda.OrderHandler
    environment:
      FUNCTION_NAME: getApiResponse